### PR TITLE
Fix Maven home detection using PATH when MAVEN_HOME is not set

### LINKED ISSUE #1547: MAVEN_HOME shouldn't need to be set
### What feature do you want to see added?

```
❯ plugin-modernizer validate
Validation error
Neither MAVEN_HOME nor M2_HOME environment variables are set. Or use --maven-home if running from CLI
```

should default to folder above where maven is I guess. My maven runs fine without setting it so why does this tool need it?

### Upstream changes

_No response_

### Are you interested in contributing this feature?

_No response_

### PR DESCRIPTION
**Pull request by s4chinjha**
This PR improves Maven detection in the plugin-modernizer tool.

Currently, the tool requires `MAVEN_HOME` or `M2_HOME` to be set, even if Maven is already available in the system `PATH`. This causes validation failures on systems where Maven is installed but environment variables are not configured.

This change adds automatic Maven detection from the system `PATH`. It uses:
- `which mvn` on Linux/macOS
- `where mvn` on Windows

to locate the Maven executable and infer the Maven home directory.

If `MAVEN_HOME` is not set, the tool now falls back to this detected path. The detected value is cached in the configuration to avoid repeated lookups.

Additionally:
- Maven validation now supports cross-platform executables (`mvn`, `mvn.cmd`, `mvn.bat`)
- Added proper handling of process execution (SpotBugs warning suppressed)

This improves usability by allowing the CLI to work out-of-the-box in environments where Maven is already available via `PATH`.

Fixes #1547

---

### Testing done

Manual testing was performed:

1. Without MAVEN_HOME:
   ```bash
   unset MAVEN_HOME
   unset M2_HOME
   java -jar jenkins-plugin-modernizer-*-SNAPSHOT.jar validate
   ```
   Result: Maven was detected from PATH and validation proceeded successfully.

2. With invalid MAVEN_HOME:
   ```bash
   export MAVEN_HOME=/invalid/path
   java -jar jenkins-plugin-modernizer-*-SNAPSHOT.jar validate
   ```
   Result: Correctly failed with "Invalid Maven home directory".

3. With valid MAVEN_HOME:
   ```bash
   export MAVEN_HOME=/usr
   java -jar jenkins-plugin-modernizer-*-SNAPSHOT.jar validate
   ```
   Result: Validation succeeded.

4. OS detection:
   Verified that Linux uses `which mvn`. Windows support is implemented via `where mvn`.

5. Build verification:
   ```bash
   mvn verify
   ```
   Result: Build succeeds. Any failing tests are due to dependency/network issues and not related to this change.

---

### Submitter checklist
- [x] Make sure you are opening from a topic/feature/bugfix branch
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues (Fixes #1547)
- [ ] Link to relevant pull requests
- [ ] Ensure you have provided tests (manual testing provided)

### CODE REVIEW

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java [hunk 1]
```diff
@@ -26,6 +26,7 @@ public static void setDebug(boolean debug) {
     private final URL githubApiUrl;
     private final Path cachePath;
     private final Path mavenHome;
+    private volatile Path detectedMavenHome;
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java]: No need volatile here. It's a CLI single thread tool

**Review by jonesbusy — APPROVED** [review]
