### PR TITLE
fix(recipes): update UpgradeNextMajorParentVersion recipe Jenkins version to 2.479.3

### LINKED ISSUE #824: UpgradeNextMajorParentVersion should use 2.479.3 and not 2.479.1
### What feature do you want to see added?

See https://github.com/jenkinsci/deepcrawl-test-plugin/pull/13#discussion_r1965403324.

### Upstream changes

_No response_

### Are you interested in contributing this feature?

_No response_

### PR DESCRIPTION
**Pull request by gounthar**
Fixes #824.

### Testing done

`mvn clean install`

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java [hunk 1]
```diff
@@ -148,9 +148,9 @@ public void getBuildableJdk() {
         assertEquals(JDK.JAVA_17, JDK.get("2.463").get(0));
         assertEquals(JDK.JAVA_21, JDK.get("2.463").get(1));
 
-        assertEquals(2, JDK.get("2.479.1").size());
-        assertEquals(JDK.JAVA_17, JDK.get("2.479.1").get(0));
-        assertEquals(JDK.JAVA_21, JDK.get("2.479.1").get(1));
+        assertEquals(2, JDK.get("2.479.3").size());
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java:151]: Not needed. Also 2.479.1 is the first LTS require java 17. So I would not change on JDK info.

**Review by jonesbusy — CHANGES_REQUESTED** [review]
I think we just need to fix the 2-3 test that fail instead of doing a search and replace here. Most of the changes are not needed I think

File: plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java [hunk 2]
```diff
@@ -2744,7 +2744,7 @@ void replaceLibrariesByApiPluginsAsm() {
                   <packaging>hpi</packaging>
                   <name>Empty Plugin</name>
                   <properties>
-                    <jenkins.version>2.479.1</jenkins.version>
+                    <jenkins.version>2.479.3</jenkins.version>
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java:2747]: Not needed. ASM removal is on 2.479.1. Not 2.479.3

File: plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml [hunk 3]
```diff
@@ -528,7 +528,7 @@ description: Check if the plugin is using a version with ASM removed
 tags: ['condition']
 recipeList:
   - org.openrewrite.jenkins.IsJenkinsPlugin:
-      version: "[2.479.1,)"
+      version: "[2.479.3,)"
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml:531]: Need to keep 2.479.1 here

**Review by jonesbusy — APPROVED** [review]
