### PR TITLE
Fix `MergeGitIgnoreRecipe` recipe 

### LINKED ISSUE #614: `MergeGitIgnoreRecipe` doesn't work
### Plugin Modernizer version

1222.vd800e48b_87e5

### What Operating System are you using

Linux WSL

### Reproduction steps

plugin-modernizer dry-run --plugins asm-api --recipe MergeGitIgnoreRecipe

Stacktrace

```
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:6.0.0:run (default-cli) on project asm-api: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:6.0.0:run failed: Error while visiting .gitignore: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   java.base/java.nio.file.Files.provider(Files.java:105) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   java.base/java.nio.file.Files.exists(Files.java:2520) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   io.jenkins.tools.pluginmodernizer.core.recipes.MergeGitIgnoreRecipe$GitIgnoreMerger.visitText(MergeGitIgnoreRecipe.java:66) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   io.jenkins.tools.pluginmodernizer.core.recipes.MergeGitIgnoreRecipe$GitIgnoreMerger.visitText(MergeGitIgnoreRecipe.java:38) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.text.PlainText.accept(PlainText.java:129) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.TreeVisitor.visit(TreeVisitor.java:157) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.scheduling.RecipeRunCycle.lambda$editSources$6(RecipeRunCycle.java:186) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:178) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.table.RecipeRunStats.recordEdit(RecipeRunStats.java:67) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.scheduling.RecipeRunCycle.lambda$editSources$7(RecipeRunCycle.java:182) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.scheduling.RecipeStack.reduce(RecipeStack.java:57) 
2025-01-11T09:04:22.470Z [INFO] [Thread=StreamPumper-systemOut] - i.j.t.p.core.impl.MavenInvoker # [ERROR]   org.openrewrite.scheduling.RecipeRunCycle.lambda$editSources$8(RecipeRunCycle.java:155) 

```

Can you take a look @nagu165 since you implemented the recipe

### Expected Results

Working

### PR DESCRIPTION
**Pull request by nagu165**
**Needs further review**
Updated the test in MergeGitIgnoreTest file to verify the logic of the recipe accurately
Working on the recipe logic

Should fix #614

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by nagu165** [comment]
Hello sir, Could you please verify the updated test and provide your intuition on why the recipe might not be working.
My guess is that it's not properly receiving/updating the archetype file

File: plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java [hunk 1]
```diff
@@ -31,75 +31,24 @@ void shouldMergeGitIgnoreEntries() {
...
-                """,
-                        sourceSpecs -> sourceSpecs.path(".gitignore")));
-    }
-
-    @Test
-    void shouldNotChangeGitIgnoreWhenNoChangesNeeded() {
-        // Test case where the existing .gitignore already contains all entries from archetype.
-        rewriteRun(
-                spec -> spec.recipe(new MergeGitIgnoreRecipe(ArchetypeCommonFile.GITIGNORE.getPath())),
-                text(
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:75]: This is still incorrect. You should have only on text(). Not 2. With one text block before and one after.

Please check other recipes

Comment (nagu165) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:75]: Small doubt sir, will it work if the archetype content varies? or are you suggesting that we can hard code the archetype file contents and should only care about the use defined contents.
Thank you.

Comment (jonesbusy) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:75]: If the content change on https://github.com/jenkinsci/archetypes/blob/master/common-files/gitignore the recipe must be adapted since we don't fetch the file but have a constant on the recipe

Comment (nagu165) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:75]: Adapted manually or the recipe must handle that also?

Comment (jonesbusy) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:75]: The .gitignore artifact is not supposed to change everyday, so it's acceptable to change it on the recipe when it changes upstream. Like it's already done now

**Comment by nagu165** [comment]
Hello sir,
I'm now fairly confident about the tests thanks to your guidance, I think now the main issue lies in how we are passing the archetype file in the constructor, Am i right?
Thank you.

**Comment by nagu165** [comment]
I have also removed the test case for "ShouldMergeEntriesInCorrectOrder" to make my work a bit easier, I'll add it once i get the confirmation regarding other tests.
Thank you.

**Comment by nagu165** [comment]
Hello sir, Could you please review the changes to the recipe and the tests. I'm sure there needs to be some more changes but need your input on them first.
Thank you.

**Comment by jonesbusy** [comment]
Please cleanup your PR first. I contains changes not related to this PR.

**Comment by nagu165** [comment]
> Please cleanup your PR first. I contains changes not related to this PR.

Done sir, I apologize for the previous commit.

File: plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java [hunk 2]
```diff
@@ -2,58 +2,58 @@
...
+import java.nio.file.Files;
+import java.nio.file.Path;
+import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.io.TempDir;
 import org.openrewrite.test.RewriteTest;
 
 public class MergeGitIgnoreRecipeTest implements RewriteTest {
 
+    @TempDir
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:15]: Don't do that. That's not how RewriteTest are working.

Please check how other rewrite test are implemented and how assertion are made 

```java
text("before", "after");
```

Comment (nagu165) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:15]: Are you suggesting about @TempDir sir?
Because i think the text format is as you have mentioned only
tempDir was already used by yourself in PluginserviceTest.
Screenshot 2025-01-13 185108

Comment (jonesbusy) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:15]: PluginServiceTest is not a test for recipe but a plain unit test

Comment (nagu165) [reply plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java:15]: Ohh ok sir, I'll modify it.
Thank you.

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java [hunk 3]
```diff
@@ -14,10 +12,11 @@
 
 public class MergeGitIgnoreRecipe extends Recipe {
     private static final Logger LOG = LoggerFactory.getLogger(MergeGitIgnoreRecipe.class);
-    private final Path archetypeGitIgnorePath;
+    private final String gitIgnoreContent;
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: Like I said (many times already) (https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912376532, https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1913126904)

This is not how OpenRewrite test are working. On assertions like 'text' you specifiy the content of the file before (the current text on the .gitignore) and the expected text after running the recipe. 

- Do not pass content to `MergeGitIgnoreRecipe` since the archetype content is a simple constant. Told https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912377410

Please take a look at other recipe that modify existing file how test are implement.

The .gitignore is not different than `UpdateScmUrlTest` for example. The only difference it's using pomXml instead of text. But it's the same

There is not need to create any file using Files since it's done by RewriteTest to prepare the environment

**Review by jonesbusy — CHANGES_REQUESTED** [review]

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java (hunk 3 above)
Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: Hello sir,
Are you suggesting that i remove this: "sourceSpecs -> sourceSpecs.path(".gitignore")" from the end of the test?
I've already tried doing that but that won't work as then it can't locate the file(.gitignore) to verify the changes made.

Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: > Like I said (many times already) ([#618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912376532), [#618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1913126904))
> 
> This is not how OpenRewrite test are working. On assertions like 'text' you specifiy the content of the file before (the current text on the .gitignore) and the expected text after running the recipe.
> 
> * Do not pass content to `MergeGitIgnoreRecipe` since the archetype content is a simple constant. Told [Updated MergeGitIgnoreRecipeTest file #618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912377410)
> 
> Please take a look at other recipe that modify existing file how test are implement.
> 
> The .gitignore is not different than `UpdateScmUrlTest` for example. The only difference it's using pomXml instead of text. But it's the same
> 
In `UpdateScmUrlTest` since we are manipulating the contents of pom we don't need to explicitly define the path right?
For text() we don need to define the path right?
> There is not need to create any file using Files since it's done by RewriteTest to prepare the environment

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: Check `testWithManyCommonFilesAndTestContainers` it's just matter of checking some existing test / code

Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: > Check `testWithManyCommonFilesAndTestContainers` it's just matter of checking some existing test / code

In this the text isn't expecting any changes hence no expected text block right?
text(
     """ Initial """,
     """ Expected after recipe applied""",
     sourceSpec()
) am i right?

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: Yes. https://github.com/openrewrite/rewrite/blob/cce9f3e7397d84b4b7de83781f17aa61e22a6a88/rewrite-test/src/main/java/org/openrewrite/test/SourceSpecs.java#L77 All information is there.

Please refer also on javadoc, framework documentation, etc

Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: > Like I said (many times already) ([#618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912376532), [#618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1913126904))
> 
> This is not how OpenRewrite test are working. On assertions like 'text' you specifiy the content of the file before (the current text on the .gitignore) and the expected text after running the recipe.
> 
> * Do not pass content to `MergeGitIgnoreRecipe` since the archetype content is a simple constant. Told [Updated MergeGitIgnoreRecipeTest file #618 (comment)](https://github.com/jenkins-infra/plugin-modernizer-tool/pull/618#discussion_r1912377410)
> 
Is it advicible to define the constant in the recipe and modify the contents from there.
> Please take a look at other recipe that modify existing file how test are implement.
> 
> The .gitignore is not different than `UpdateScmUrlTest` for example. The only difference it's using pomXml instead of text. But it's the same
> 
> There is not need to create any file using Files since it's done by RewriteTest to prepare the environment

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: It's a constant. You don't modify a constant.

OpenRewrite LTS are immutable. You return a new file with new content using 

```java
return text.withText("my amazin new file");
```

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: See https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#recipes-must-not-mutate-lsts

You should not mutate LST, but instead return a new Tree

Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java:15]: > It's a constant. You don't modify a constant.
> 
I was talking about modifying the contents of gitignore file, sorry for not conveying properly.
> OpenRewrite LTS are immutable. You return a new file with new content using
> 
> ```java
> return text.withText("my amazin new file");
> ```

**Comment by nagu165** [comment]
Defined the constant in the Recipe file itself and merging the contents using it. Is this acceptable?

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java [hunk 4]
```diff
@@ -12,12 +12,18 @@
 
 public class MergeGitIgnoreRecipe extends Recipe {
     private static final Logger LOG = LoggerFactory.getLogger(MergeGitIgnoreRecipe.class);
-    private final String gitIgnoreContent;
 
-    public MergeGitIgnoreRecipe(String gitIgnoreContent) {
-        this.gitIgnoreContent = gitIgnoreContent;
-        LOG.info("updated MergeGitIgnoreRecipe with given .gitignore content.");
-    }
+    private static final String ARCHETYPE_GITIGNORE_CONTENT = """
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java]: Doesn't match https://github.com/jenkinsci/archetypes/blob/master/common-files/gitignore

Comment (nagu165) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java]: Does the final gitignore file also need to have the exact format ( spaces and comments ) or can we omit them?

**Comment by nagu165** [comment]
Hello sir, Are there still any improvements required in this? or am i missing something.
Thank you.

**Comment by jonesbusy** [comment]
Hi. I think we are good to go. I'll merge and perform some interactive tests tomorrow (and probably do a release if time permits)

**Review by jonesbusy — APPROVED** [review]
