### PR TITLE
Fix JDK provisioning on macOS (ARM64) by supporting Contents/Home structure

### LINKED ISSUE #1377: [Bug] JDK provisioning fails on macOS (ARM64) due to incorrect bin path extraction
### Plugin Modernizer version

Built from source (main branch)

### What Operating System are you using

macOS Sequoia (ARM64 / Apple Silicon)

### Reproduction steps

1. Build the tool from source on a macOS ARM64 machine:
   `mvn clean install -DskipTests`

2. Run a dry-run against any local plugin (e.g., a hello-world plugin):
   `java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar dry-run --plugin-path ../my-first-plugin --recipe AddPluginsBom --debug`

3. Observe the output during the JDK provisioning phase.

### Expected Results

The tool should successfully locate the `bin` directory inside the extracted JDK and proceed to set permissions and run the recipe.

**Actual Behavior:**
The tool crashes because it expects the `bin` folder to be at the root of the extracted directory. On macOS, JDKs often extract with the structure `jdk.jdk/Contents/Home/bin`.

**Logs:**
```text
Downloading the JDK...
Download successful
Extracting...
Setting executable permissions for files in bin directory
The bin directory does not exist: /Users/username/.cache/jenkins-plugin-modernizer-cli/.jdks/plugin-modernizer-jdk-21/bin
Extraction successful
Build failed

### PR DESCRIPTION
**Pull request by alphaleporus**
Fixes #1377

This PR fixes a crash when running the tool on macOS (specifically tested on Apple Silicon/M1).

The `JdkFetcher` previously assumed that the `bin` directory is always located at the root of the extracted JDK folder. However, on macOS, JDKs are often bundled with the structure `jdk.jdk/Contents/Home/bin`. This caused the tool to fail with "The bin directory does not exist" immediately after downloading the JDK.

**Changes:**
- Updated `setJavaBinariesPermissions` in `JdkFetcher.java` to check for `Contents/Home/bin` if the standard `bin` directory is missing.
- Updated `getJdkPath` in `JdkFetcher.java` to return the `Contents/Home` directory on macOS so that downstream commands can correctly locate the `java` executable.

### Testing done

I manually verified this fix on a MacBook Air (M1, macOS Sequoia) where the tool was previously crashing.

**Steps performed:**
1. Built the tool from source: `mvn clean install -DskipTests`
2. Ran a dry-run against a local test plugin:
   `java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar dry-run --plugin-path ../my-first-plugin --recipe AddPluginsBom`

**Result:**
- **Before:** Crashed with `The bin directory does not exist` during extraction.
- **After:** Successfully detected the JDK home at `.../Contents/Home`, set permissions, and proceeded to execute the Maven goal.

Logs from successful run:
```text
JDK home: /Users/gauravsharma/.cache/jenkins-plugin-modernizer-cli/.jdks/plugin-modernizer-jdk-21/Contents/Home

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JdkFetcher.java [hunk 1]
```diff
@@ -56,6 +56,18 @@ public Path getJdkPath(int jdkVersion) throws IOException, InterruptedException
...
+        // [Fix] Handle macOS JDK structure (Contents/Home)
+        // If the standard bin directory doesn't exist, check for the macOS specific path
+        if (!Files.isDirectory(jdkPath.resolve("bin"))) {
+            Path macOsHome = jdkPath.resolve("Contents").resolve("Home");
+            if (Files.isDirectory(macOsHome)) {
+                return macOsHome;
+            }
+        }
+        // [Debug] Print the path we are returning
+        LOG.info("Resolved JDK Path for version {}: {}", jdkVersion, jdkPath);
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JdkFetcher.java]: LOG is not printed if directory is on OSC

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JdkFetcher.java [hunk 2]
```diff
@@ -56,6 +56,18 @@ public Path getJdkPath(int jdkVersion) throws IOException, InterruptedException
         if (Files.notExists(jdkPath)) {
             downloadAndSetupJdk(jdkVersion, jdkPath);
         }
+
+        // [Fix] Handle macOS JDK structure (Contents/Home)
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JdkFetcher.java]: Useless comment. AI?

**Review by jonesbusy — APPROVED** [review]
